name: Microservices CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ai_service, logger_service]

    env:
      AWS_REGION: us-east-1
      IMAGE_NAME: mindful-ai-${{ matrix.service }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # ✅ Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Login to AWS ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ✅ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME ${{ matrix.service }}

      # ✅ Tag & Push to Docker Hub
      - name: Tag & Push to Docker Hub
        run: |
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      # ✅ Tag & Push to AWS ECR
      - name: Tag & Push to AWS ECR
        run: |
          ECR_REPO_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/$IMAGE_NAME
          docker tag $IMAGE_NAME $ECR_REPO_URI:latest
          docker push $ECR_REPO_URI:latest
