name: Microservices CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ai_service, logger_service]

    env:
      AWS_REGION: us-east-1
      IMAGE_NAME: mindful-ai-${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r ${{ matrix.service }}/requirements.txt

      - name: Lint code
        run: |
          source venv/bin/activate
          python -m py_compile ${{ matrix.service }}/app.py

      ###########################
      ## 🔐 Docker Hub Login
      ###########################
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      ###########################
      ## 🐳 Build and Push to Docker Hub
      ###########################
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mindful-ai-${{ matrix.service }}:latest

      ###########################
      ## 🔐 AWS ECR Login
      ###########################
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      ###########################
      ## 🐳 Build and Push to ECR
      ###########################
      - name: Build and push Docker image to Amazon ECR
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:latest
