name: Microservices CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ai_service, logger_service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r ${{ matrix.service }}/requirements.txt

      - name: Lint code (optional)
        run: |
          source venv/bin/activate
          python -m py_compile ${{ matrix.service }}/app.py

